ARG BASE_IMAGE=localhost/aisb-base:latest
FROM ${BASE_IMAGE}

ARG PI_VERSION=unknown
RUN echo "pi-coding-agent version: ${PI_VERSION}" \
 && test "${PI_VERSION}" != "unknown" \
 && npm install -g "@mariozechner/pi-coding-agent@${PI_VERSION}"

ENTRYPOINT ["pi"]
